tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/HabersayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class HabersayfaController : Controller
    {
        tartiilebarisEntities db = new tartiilebarisEntities();
        // GET: Admin/Habersayfa
        [Authorize(Roles = "editor")]
        public ActionResult Index()
        {
            var liste = db.habersayfa.ToList();
            return View(liste);
        }

        public ActionResult habersayfaAdd()
        {
            return View();
        }
        public ActionResult addhabersayfa(habersayfa model)
        {
            if (ModelState.IsValid)
            {
                db.habersayfa.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult habersayfaedit(int id)
        {
            var model = db.habersayfa.Find(id);
            //db.slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult habersayfaedit(habersayfa model)
        {
            if (ModelState.IsValid)
            {
                db.habersayfa.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult habersayfadelete(int id)
        {
            var model = db.habersayfa.Find(id);
            db.habersayfa.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //public ActionResult deletehaberler(int id)
        //{
        //    var model = db.haberler.Find(id);
        //    db.haberler.Remove(model);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}


    }
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Habersayfa/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tables</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Haber Sayfası Tablosu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Başlık</th>
                                <th>Açıklama</th>
                                <th>Resim</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.baslik</td>
                                    <td>@item.yanbaslik</td>
                                    <td>@item.aciklama</td>

                                    <td>@item.resim</td>

                                    <td>@Html.ActionLink("Düzenle", "habersayfaedit", "Habersayfa", new { id = item.ID }, null)|@Html.ActionLink("Sil", "habersayfadelete", "Habersayfa", new { id = item.ID }, null)</td>
                                </tr>

                            }
                            @Html.ActionLink("Ekle", "habersayfaAdd", "Habersayfa")
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Habersayfa/habersayfaAdd.cshtml
@model tartiilebaris.habersayfa

@{
    ViewBag.Title = "habersayfaAdd";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yeni Haber Sayfası Ekle</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Haberler
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">

                        @using (Html.BeginForm("addhabersayfa", "Habersayfa", FormMethod.Post))
                        {
                            <div class="form-group">
                                @Html.LabelFor(m => m.baslik)
                                @Html.TextBoxFor(m => m.baslik, new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.yanbaslik)
                                @Html.TextBoxFor(m => m.yanbaslik, new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.aciklama)
                                @Html.TextAreaFor(m => m.aciklama, new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.resim)
                                @Html.TextBoxFor(m => m.resim, new { @class = "form-control" })

                            </div>

                            <button type="submit" class="btn btn-default">Ekle</button>

                        }
                    </div>


                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Habersayfa/habersayfadelete.cshtml
@model tartiilebaris.habersayfa

@{
    ViewBag.Title = "habersayfadelete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>habersayfadelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>habersayfa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.yanbaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.yanbaslik)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Habersayfa/habersayfaedit.cshtml
@model tartiilebaris.saglilibeslenme

@{
    ViewBag.Title = "sagliklibeslenmeedit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Saglilibeslenme Sayfasını Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.resim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>