tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/HaberlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class HaberlerController : Controller
    {
        tartiilebarisEntities db = new tartiilebarisEntities();
        // GET: Admin/Haberler
        [Authorize(Roles = "editor")]
        public ActionResult Index()
        {
            var liste = db.haberler.ToList();
            return View(liste);
        }
        public ActionResult HaberlerAdd()
        {
            return View();
        }
        public ActionResult addhaberler(haberler model)
        {
            if (ModelState.IsValid)
            {
                db.haberler.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult haberleredit(int id)
        {
            var model = db.haberler.Find(id);
            //db.slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult haberleredit(haberler model)
        {
            if (ModelState.IsValid)
            {
                db.haberler.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult haberlerdelete(int id)
        {
            var model = db.haberler.Find(id);
            db.haberler.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //public ActionResult deletehaberler(int id)
        //{
        //    var model = db.haberler.Find(id);
        //    db.haberler.Remove(model);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

    }
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Haberler/HaberlerAdd.cshtml
@model tartiilebaris.haberler

@{
    ViewBag.Title = "HaberlerAdd";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yeni Haber Ekle</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Haberler
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">

                        @using (Html.BeginForm("addhaberler", "Haberler", FormMethod.Post))
                        {
                            <div class="form-group">
                                @Html.LabelFor(m => m.baslik)
                                @Html.TextBoxFor(m => m.baslik, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.aciklama)
                                @Html.TextAreaFor(m => m.aciklama, new { @class = "form-control" })
                            </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.resim)
                                    @Html.TextBoxFor(m => m.resim, new { @class = "form-control" })

                                </div>

                                <button type="submit" class="btn btn-default">Ekle</button>

                        }
                    </div>


                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Haberler/Index.cshtml
@model List<haberler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablolar</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Haberler Tablosu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Başlık</th>
                                <th>Açıklama</th>
                                <th>Resim</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.baslik</td>
                                    <td>@item.aciklama</td>
                                    <td>@item.resim</td>

                                    <td>@Html.ActionLink("Düzenle", "haberleredit", "Haberler", new { id = item.ID }, null)|@Html.ActionLink("Sil", "haberlerdelete", "Haberler", new { id = item.ID }, null)</td>
                                </tr>
                            }
                            @Html.ActionLink("Ekle", "HaberlerAdd", "Haberler")
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Haberler/haberlerdelete.cshtml
@model tartiilebaris.haberler

@{
    ViewBag.Title = "haberlerdelete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>haberlerdelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>haberler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.src)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.src)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Haberler/haberleredit.cshtml
@model tartiilebaris.haberler

@{
    ViewBag.Title = "haberleredit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Hberler Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>haberler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.resim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.resim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.src, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.src, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.src, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>