tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/KullaniciController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tartiilebaris.Models;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class KullaniciController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/Kullanici
        [Authorize(Roles = "yonetici")]
        public ActionResult Index()
        {
            var rolestore = new RoleStore<IdentityRole>(context);
            var rolmanager = new RoleManager<IdentityRole>(rolestore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            var model = userManager.Users.ToList();
            return View(model);
        }
        public ActionResult kullanicidelete(int id)
        {
            var model =context.Find(id);
            context.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
   
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/RolYonetimiController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tartiilebaris.Areas.Admin.Models;
using tartiilebaris.Models;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class RolYonetimiController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/RolYonetimi
        [Authorize(Roles = "yonetici")]
        public ActionResult Index()
        {
            var rolestore = new RoleStore<IdentityRole>(context);
            var rolmanager = new RoleManager<IdentityRole>(rolestore);

            var model = rolmanager.Roles.ToList();
            return View(model);
        }
        public ActionResult rolekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult rolekle(roleklemodel rol)
        {
            var rolestore = new RoleStore<IdentityRole>(context);
            var rolmanager = new RoleManager<IdentityRole>(rolestore);

            if (rolmanager.RoleExists(rol.rolad)==false)
            {
                rolmanager.Create(new IdentityRole(rol.rolad));
            }
            return RedirectToAction("Index");

        }
        public ActionResult rolkullaniciekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult rolkullaniciekle(rolkullanicieklemodel model)
        {
            var rolestore = new RoleStore<IdentityRole>(context);
            var rolmanager = new RoleManager<IdentityRole>(rolestore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var kullanici = userManager.FindByName(model.kullaniciad);

            if (!userManager.IsInRole(kullanici.Id, model.rolad))
            {
                userManager.AddToRole(kullanici.Id, model.rolad);
            }
            return RedirectToAction("Index");
        }
    }
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Kullanici/Index.cshtml
@model List<tartiilebaris.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablolar</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Kullanıcılar Tablosu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Email</td>
                                    <td>
                                        @Html.ActionLink("Rol Ver", "rolkullaniciekle","RolYonetimi")||@Html.ActionLink("Sil", "kullanicidelete", "Kullanici", new { id = item.Id }, null)
                                    </td>

</tr>

                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>