tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/EgzersizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class EgzersizController : Controller
    {
        tartiilebarisEntities db = new tartiilebarisEntities();
        // GET: Admin/Egzersiz
        [Authorize(Roles = "editor")]
        public ActionResult Index()
        {
            var liste = db.egzersiz.ToList();
            return View(liste);
        }
        public ActionResult EgzersizAdd()
        {
            return View();
        }
        public ActionResult addegzersiz(egzersiz model)
        {
            if (ModelState.IsValid)
            {
                db.egzersiz.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult egzersizedit(int id)
        {
            var model = db.egzersiz.Find(id);
            //db.slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult egzersizedit(egzersiz model)
        {
            if (ModelState.IsValid)
            {
                db.egzersiz.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult egzersizdelete(int id)
        {
            var model = db.egzersiz.Find(id);
            db.egzersiz.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //public ActionResult deletehaberler(int id)
        //{
        //    var model = db.haberler.Find(id);
        //    db.haberler.Remove(model);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

    }
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tartiilebaris.Areas.Admin.Controllers
{
    public class IletisimController : Controller
    {
        tartiilebarisEntities db = new tartiilebarisEntities();
        // GET: Admin/Egzersiz
        [Authorize(Roles = "editor")]
        public ActionResult Index()
        {
            var liste = db.iletisim.ToList();
            return View(liste);
        }
        public ActionResult iletisimAdd()
        {
            return View();
        }
        public ActionResult addiletisim(iletisim model)
        {
            if (ModelState.IsValid)
            {
                db.iletisim.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult iletisimedit(int id)
        {
            var model = db.iletisim.Find(id);
            //db.slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult iletisimedit(iletisim model)
        {
            if (ModelState.IsValid)
            {
                db.iletisim.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult iletisimdelete(int id)
        {
            var model = db.iletisim.Find(id);
            db.iletisim.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //public ActionResult deletehaberler(int id)
        //{
        //    var model = db.haberler.Find(id);
        //    db.haberler.Remove(model);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

    }
}

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Iletisim/Index.cshtml
@model List<iletisim>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablolar</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Egzersizler Tablosu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Email</th>
                                <th>Yorum</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.mail</td>
                                    <td>@item.yorum</td>

                                    <td>@Html.ActionLink("Düzenle", "iletisimedit", "Iletisim", new { id = item.ID }, null)|@Html.ActionLink("Sil", "iletisimdelete", "Iletisim", new { id = item.ID }, null)</td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Iletisim/iletisimAdd.cshtml
@model tartiilebaris.iletisim

@{
    ViewBag.Title = "iletisimAdd";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yeni Egzersiz Ekle</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Egzersizler
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">

                        @using (Html.BeginForm("addegzersiz", "Egzersiz", FormMethod.Post))
                        {
                            <div class="form-group">
                                @Html.LabelFor(m => m.mail)
                                @Html.TextBoxFor(m => m.mail, new { @class = "form-control" })


                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.yorum)
                                @Html.TextAreaFor(m => m.yorum, new { @class = "form-control" })

                            </div>
                            <button type="submit" class="btn btn-default">Ekle</button>

                        }
                    </div>


                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Iletisim/iletisimdelete.cshtml
@model tartiilebaris.iletisim

@{
    ViewBag.Title = "iletisimdelete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>iletisimdelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>iletisim</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.yorum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.yorum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tartiilebaris-mvcproje/tartiilebaris/Areas/Admin/Views/Iletisim/iletisimedit.cshtml
@model tartiilebaris.iletisim

@{
    ViewBag.Title = "iletisimedit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>iletisimedit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>iletisim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.yorum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.yorum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.yorum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>